# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json for the client
COPY client/package*.json ./client/

# Install client dependencies
RUN cd client && npm install

# Copy package.json and package-lock.json for the server
COPY server/package*.json ./server/

# Install server dependencies
RUN cd server && npm install

# Copy the client code into the container at /app/client
COPY client/ ./client/

# Copy the server code into the container at /app/server
COPY server/ ./server/

# Expose ports
EXPOSE 3000 5000

# Define environment variable
ENV NODE_ENV=production

# Command to run your application
CMD ["npm", "start"]
